export const initData = {
    data: [
        {
            id: 1,
            title: 'board test ',
            destroy: false,
            account: {
                id: 1,
                username: 'test',
                password: '**********',
                fullName: null,
                email: 'test@gmail.com',
                avatar: 'ads',
                role: 'ADMIN',
                status: true,
            },
            accountId: 1,
            columns: [
                {
                    id: 1,
                    title: 'Test 1',
                    columnOrder: 1,
                    destroy: false,
                    board: null,
                    boardId: 1,
                    cards: [
                        {
                            id: 1,
                            title: 'Card Test 1',
                            cover: 'https://images.unsplash.com/photo-1683661649729-1053579e0d22?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=884&q=80',
                            cardOrder: 1,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 1,
                        },
                        {
                            id: 9,
                            title: 'Card Test 9',
                            cover: null,
                            cardOrder: 9,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 2,
                        },
                    ],
                },
                {
                    id: 2,
                    title: 'Test 2',
                    columnOrder: 2,
                    destroy: false,
                    board: null,
                    boardId: 1,
                    cards: [
                        {
                            id: 1,
                            title: 'Card Test 1',
                            cover: null,
                            cardOrder: 1,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 2,
                        },
                        {
                            id: 5,
                            title: 'Card Test 5',
                            cover: null,
                            cardOrder: 2,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 2,
                        },
                        {
                            id: 2,
                            title: 'Card Test 2',
                            cover: null,
                            cardOrder: 3,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 2,
                        },
                        {
                            id: 6,
                            title: 'Card Test 6',
                            cover: null,
                            cardOrder: 4,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 2,
                        },
                        {
                            id: 4,
                            title: 'Card Test 4',
                            cover: null,
                            cardOrder: 5,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 2,
                        },
                        {
                            id: 3,
                            title: 'Card Test 3',
                            cover: null,
                            cardOrder: 6,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 2,
                        },
                    ],
                },
                {
                    id: 3,
                    title: 'Test 3 ',
                    columnOrder: 3,
                    destroy: false,
                    board: null,
                    boardId: 1,
                    cards: [
                        {
                            id: 3,
                            title: 'Card Test 3',
                            cover: null,
                            cardOrder: 1,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 3,
                        },
                        {
                            id: 2,
                            title: 'Card Test 2',
                            cover: null,
                            cardOrder: 2,
                            destroy: false,
                            board: null,
                            boardId: 1,
                            column: null,
                            columnId: 3,
                        },
                    ],
                },
            ],
        },
        {
            id: 2,
            title: 'board test 2',
            destroy: false,
            account: {
                id: 1,
                username: 'test',
                password: '**********',
                fullName: null,
                email: 'test@gmail.com',
                avatar: 'ads',
                role: 'ADMIN',
                status: true,
            },
            accountId: 1,
            columns: [],
        },
    ],
}
